# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Circle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  # Pods for Circle

  target 'CircleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CircleUITests' do
    # Pods for testing
  end

end
